Fixes a lot of mnemonics and compiler errors.

diff --git a/dos/Makefile b/dos/Makefile
--- a/dos/Makefile
+++ b/dos/Makefile
@@ -1,5 +1,6 @@
 AS=../assembler/assembler
 SIM=../emulator/simulator.exe
+STTYVAL=$(shell stty -g)
 
 all: dos.hex
 
@@ -7,7 +8,7 @@ dos.hex: dos.inc
 	echo -e "\033[31;1mAssemble...\033[0m"
 	$(AS) -s -o $@ $<
 
-dos.inc: interrupts.asm main.asm syscall.asm puts.asm
+dos.inc: interrupts.asm main.asm syscall.asm puts.asm itoa.asm
 	echo -e "\033[31;1mPack...\033[0m"
 	echo '; ' $^ > $@.proto
 	echo '#include "macros.inc"' >> $@.proto
@@ -22,6 +23,8 @@ run: dos.hex
 trace: dos.hex
 	echo -e "\033[31;1mTrace...\033[0m"
 	cat $<
-	$(SIM) --trace
+	cat $< | xclip -in
+	gdb $(SIM) || echo "failed simulation!"
+	stty $(STTYVAL)
 	
 .PHONY: run trace
